### ISSUE TITLE
Explicit 'count' field in AccelerationStructureBuildGeometryInfoKHR

### ISSUE THREAD

**Issue by sheaf** [expipiplus1/vulkan#239] opened 2020-12-11 06:08 UTC
I'm wondering why `AccelerationStructureBuildGeometryInfoKHR` has an explicit `geometryCount` field, as this is just supposed to be the size of the `geometries` vector. In other places in this library, this field is usually elided.    
I assume that this ended up being a special case, because the original Vulkan function can work with either a pointer to an array of geometries or a pointer to an array of pointers to geometries?

> - Only one of pGeometries or ppGeometries can be a valid pointer, the other must be NULL
> - If geometryCount is not 0, and pGeometries is not NULL, pGeometries must be a valid pointer to an array of geometryCount valid AccelerationStructureGeometryKHR structures
> - If geometryCount is not 0, and ppGeometries is not NULL, ppGeometries must be a valid pointer to an array of geometryCount valid pointers to valid AccelerationStructureGeometryKHR structures

**Comment by expipiplus1** [comment] 2020-12-11 09:00
This is a deficiency in the bindings.

The cause is:

Lengths are elided if they can be uniquely determined by the lengths of `Vector`s being passed. In this case both arrays which are sized by this length are `optional`:

https://github.com/KhronosGroup/Vulkan-Docs/blob/8f718b4194ed1e0a572d37072e5558dd9ceabcb0/xml/vk.xml#L4772-L4774

This means that (according to just the XML spec) one could pass a length and NULL for both vectors. The XML spec lacks the language to say that only one of these arrays can be NULL.

Usually there's a 1-1 mapping between arrays and `Vector`s, however in this specific case we ditch `ppGeometries` and make `pGeometries` mandatory. 

The easiest solution would be to assign it `ElidedLength ["pGeometries"] []` (or something like that) here: https://github.com/expipiplus1/vulkan/blob/8ba913e2ba1076f59d9325d974429816fb6e83a4/generate-new/src/Bespoke.hs#L612-L618. I can take a look at this next week

For now it's safe to set it to zero and it'll be inferred: https://github.com/expipiplus1/vulkan/blob/8ba913e2ba1076f59d9325d974429816fb6e83a4/src/Vulkan/Extensions/VK_KHR_acceleration_structure.hs#L5386-L5387

**Comment by sheaf** [comment] 2020-12-11 11:56
This obviously isn't causing me any trouble at all so you don't need to worry about it.

**Comment by expipiplus1** [comment] 2021-01-09 08:59
Fixed with https://github.com/expipiplus1/vulkan/pull/251

**Closed** 2021-01-09 09:02 UTC
