### ISSUE TITLE
Windows build instructions

### ISSUE THREAD

**Issue by dpwiz** [expipiplus1/vulkan#97] opened 2020-05-10 08:10 UTC
Readme (or wiki) should document how to get dependencies (easy with stack) and extra tweaks in code to build e.g. triangle example.

**Comment by expipiplus1** [comment] 2020-05-10 09:23
Absolutely, the ci should also be made to run on windows and osx too.

I don't have a windows machine for Haskell, but would happily accept a PR from anyone who does and is able to test.

**Comment by expipiplus1** [comment] 2020-05-18 11:58
@dpwiz, Have you got things running on Windows, and do you have a list of these tweaks?

**Comment by dpwiz** [comment] 2020-05-18 12:04
I've got the application to run, but stuck with "khr win32 surface extension not present" error, with it being explicitly requested (by SDL itself) on instance creation.

**Comment by expipiplus1** [comment] 2020-05-18 14:41
@dpwiz I've build and run the applications on windows. They seem to work if I run them via `stack repl` but not `stack run` I guess a different loader is being linked.

**Comment by expipiplus1** [comment] 2020-05-18 15:58
The `compute` example works with `stack run` (with the validation extension disabled). It looks as though `stack run` causes no loader to be consulted. Windows development is a disaster

**Comment by expipiplus1** [comment] 2020-05-18 16:32
So ghc segfaults building deps on windows... https://github.com/expipiplus1/vulkan/pull/115/checks?check_run_id=686009472

**Comment by expipiplus1** [comment] 2020-05-19 04:19
Indeed, looking at the loaded DLLs with Process Explorer, C:/Windows/System32/vulkan-1.dll is loaded when things work in the repl, but c:/sr/...stack/..msys2/...vulkan/bin/vulkan-1.dll is loaded with `stack run`

**Comment by expipiplus1** [comment] 2020-05-19 08:36
@dpwiz Could you check the instructions on the `windows` branch please and check that they work for you https://github.com/expipiplus1/vulkan/pull/115/files#diff-0730bb7c2e8f9ea2438b52e419dd86c9R301-R324

On that branch you should be able to:

- Build `vulkan` and all the examples
- Use `stack --extra-lib-dirs=... repl vulkan-examples:{resize,sdl-triangle,compute,...}` to enter a repl capable of running any example
- Use `stack --extra-lib-dirs=... run {resize,sdl-triangle,compute,...}` to run any example
  - Messages printed to the console should be visible here

The only thing not working for me are HiDPI windows for the SDL examples.

**Comment by expipiplus1** [comment] 2020-05-19 08:44
https://discourse.libsdl.org/t/sdl-getdesktopdisplaymode-resolution-reported-in-windows-10-when-using-app-scaling/22389/4 could help with the hidpi problem.

**Comment by dpwiz** [comment] 2020-05-20 09:29
My attempts to run were thwarted on four side :sweat_smile: 

GHC-8.8.3 crashes on start, 8.8.2 fails to link examples (the fix was merged in 8.8.3, but alas). 8.6.5 fails on building autoapply. My playground still can't find the extension needed and the `funPtr` given by instances is indeed 0x000...

**Comment by expipiplus1** [comment] 2020-05-20 12:57
Oh man, that's a pain.

This might help RE the extensions, untested though https://github.com/expipiplus1/vulkan/pull/116/commits/f5d41308adf3eb89fa4167fc91e9a98458c54796

FWIW 8.8.3 with stack worked well for me. It does seem like GHC is pretty broken on windows at the moment though.

**Comment by dpwiz** [comment] 2020-07-11 20:19
I finally got to try again, this time with a nightly stackage and GHC 8.10. The SDL still fails with "instance missing extensions". Your examples do indeed run from repl, but not from the build. Even with `SDL.vkLoadLibrary` requested the real thing explicitly before window creation. Furthermore, I've [tried](https://gitlab.com/snippets/1994958) using GLFW wrapper to exact same effect: the library prompts to add khr_win32 extension and then fails for it isn't available in instance.

**Comment by expipiplus1** [comment] 2020-07-13 03:37
hmm, my guess would be that mingw's vulkan-1.dll is being loaded instead of `C:/Windows/System32/vulkan-1.dll`. The interaction with SDL is confusing, SDL loads the DLL explicitly, but the `vulkan` package relies on the system linker to do everything, if these end up loading different DLLs them things are liable to break. 

I can try to reproduce this tonight. Any of the below would be helpful:

- Exact repro instructions 
  - I guess they are the same as here https://github.com/expipiplus1/vulkan#building-on-windows and all but the last step works.
- Looking at what DLLs are loaded (specifically vulkan-1.dll) using process explorer
- Seeing if the loaded DLLs can be queried by a running program and dumped to console, having the examples print this information would be very useful in debugging issues like this in the future.

**Comment by expipiplus1** [comment] 2020-07-13 11:58
`stack --extra-lib-dirs=C:/VulkanSDK/1.2.135.0/Lib run resize` still works for me (with both 8.8.3 and 8.10.1)

**Comment by dpwiz** [comment] 2020-07-13 20:17
I updated my stack `extra-lib-dirs` with extra `Lib` and it stopped crapping on extensions. I can now run your examples (resize crashes on resize though).

**Comment by expipiplus1** [comment] 2020-07-14 03:55
Quite possible, I'm sure I made some invalid assumptions according to the spec. 

What hardware are you running? (output of vkinfo, or even the `info` haskell program would be useful)

I'm guessing it's just an access violation and doesn't have a nice error message.

**Comment by dpwiz** [comment] 2020-07-14 08:08
Resize:

```
Validation: Validation Error: [ VUID_Undefined ] Object 0: handle = 0x1307bcc0, type = VK_OBJECT_TYPE_DEVICE; | MessageID = 
0x79de34d4 | vkWaitForFences: parameter fenceCount must be greater than 0.
resize.EXE: UnliftIO.Exception.throwString called with:

Unexpected Result from acquireNextImageKHR
Called from:
  throwString (resize\Main.hs:234:12 in main:Main)
```

My playground:

```
Access violation in generated code when reading 0x28

 Attempting to reconstruct a stack trace...

   Frame        Code address
 * 0x33eda90    0x7ffc13778301 C:\WINDOWS\System32\DriverStore\FileRepository\u0353595.inf_amd64_d09a62a4ca6a5064\B353566\amdvlk64.dll+0x48301
 * 0x33eda98    0xd87f1a C:\src\playground3\.stack-work\install\d679a363\bin\playground3.EXE+0x987f1a
 * 0x33edaa0    0x8
```

**Comment by expipiplus1** [comment] 2020-07-14 08:25
OK, the validation error makes sense, the incorrect assumption was that zero fences was allows in a call to `vkWaitForFences` (why can't it be specified to immediately return with success!).

The `Unexpected Result from acquireNextImageKHR` is because it's returning either `VK_NOT_READY` or `VK_SUBOPTIMAL_KHR`. which aren't handled. The latter should probably just do that same thing as the case for `VK_SUCCESS`. Not sure what to do off the top of my head for `VK_NOT_READY`.

So: the fix is to handle those two cases, and also check that there are fences to wait on before waiting.

My guess is that it's `VK_SUBOPTIMAL` and adding the suggested handling for that case should fix things.

**Comment by expipiplus1** [comment] 2020-09-10 07:05
Closing now that we have Windows builds with Stack in CI

**Closed by expipiplus1** 2020-09-10 07:05 UTC
